# Generated by Django 2.0.5 on 2018-06-02 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=250)),
                ('Roll_No', models.CharField(max_length=10)),
                ('Branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Data.Students'),
        ),
    ]
