# Generated by Django 2.0.5 on 2018-06-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_Name', models.CharField(max_length=200)),
                ('Course_Code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Credits', models.IntegerField()),
                ('No_of_Lectures', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_Name', models.CharField(max_length=50)),
                ('Roll_No', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Branch', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=10)),
                ('Reg_Course', models.ManyToManyField(to='Student_Data.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='students',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
