# Generated by Django 2.0.5 on 2018-06-07 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Data', '0002_auto_20180606_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='MA106',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MA106_Date',
            fields=[
                ('Date', models.DateField(default='2018-06-07', primary_key=True, serialize=False)),
                ('Status', models.CharField(default='NA', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='ma106',
            name='ma106_dates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Data.MA106_Date'),
        ),
        migrations.AddField(
            model_name='ma106',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Data.Student'),
        ),
    ]
