# Generated by Django 2.0.5 on 2018-06-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Data', '0003_auto_20180607_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ma106',
            name='ma106_dates',
        ),
        migrations.AddField(
            model_name='ma106',
            name='ma106_dates',
            field=models.ManyToManyField(to='Student_Data.MA106_Date'),
        ),
    ]
