# Generated by Django 2.0.5 on 2018-06-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Data', '0004_auto_20180607_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ma106',
            name='ma106_dates',
        ),
        migrations.AddField(
            model_name='ma106',
            name='June_4_2018',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.DeleteModel(
            name='MA106_Date',
        ),
    ]
