# Generated by Django 2.0.5 on 2018-06-07 10:00

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Data', '0006_auto_20180607_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma106',
            name='Attendance',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=[], max_length=22, size=2),
        ),
    ]
