# Generated by Django 2.0.5 on 2018-06-07 10:04

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Data', '0007_ma106_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ma106',
            name='Attendance',
            field=django_mysql.models.ListCharField(models.CharField(max_length=2), default=[], max_length=48, size=16),
        ),
    ]
