# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Data', '0008_auto_20180607_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MA106_Date',
        ),
    ]
