# Generated by Django 2.0.5 on 2018-06-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Data', '0010_cs101_ma105_ph108'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Student_Image'),
        ),
    ]
